name: Publish Docker image

on:
  release:
    types: [published]
  push:
    {}
  workflow_dispatch:
    {}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Fetch Repo Name
         id: repo-name
         run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"

      - name: build-push
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ steps.repo-name.outputs.value }}
          tag_with_ref: true
          push: true
          always_pull: true
          add_git_labels: true
